### ISSUE TITLE
HashMap Problem

### ISSUE THREAD

**Issue by zek** [midiway/sciter-dport#2]
I've called function with
        view.function(1, 2, 3, 4, 5, "zack", {'a': 'b', 't': 'q'}, [123,456]);

then catched it like this:
        foreach(i, param; prms.argv[0..prms.argc]){
            writeln(i, ": ", json_value(param).to_string());
        }
but output is wrong
0: 1
1: 2
2: 3
3: 4
4: 5
5: "zack"
6: {
        ""      :98}
7: [123, 456]

It fails only hashmaps.

**Comment by midiway** [comment]
plz, explain your problem more clearly, where did you called that function, as TIScript from an html page I guess...
And how are catching it? I guess a native event handler attached to the Sciter HWND?

**Comment by zek** [comment]
Yes. I've called it from html page then catched it with native event handler.
Any type of data works fine except objects (hashmaps)

**Comment by midiway** [comment]
ok, I checked, the bug in Sciter library itself in the way it handles object with integer fields, like
´´´{ 12: "whatever" }´´´
I can't solve it, plz contact Sciter author

**Comment by c-smile** [comment]
In TIScript  'a' is an integer literal - unicode code point of 'a'. In the same way as in C/C++ and D.
To drtzack: you should use strings: {"a": "b", "t": "q"} there.
